proc iml;
print 'The Theoretical Distribution of X';
x=(2:12)`;
f=(6-abs(x-7))/36;
FF=cusum(f);
print x f [format=10.4] FF [format=10.4];
print 'The Empirical Distribution of X';
p=J(1,6,1)/6;
call randseed(123,1);
dice=randfun({1000,2},'table',p);
sum=dice[,+];
matrix=dice||sum;
create DDICE from matrix[colname={'roll1' 'roll2' 'sum'}];
append from matrix;
quit;
proc freq data=DDICE;
tables roll1 roll2 sum;
title 'The frequency distribution of X';
run;
